// 法師群 (magician branch) 共通技能 — barrel,彙整 0~6 轉
//
// 適用職業:archmageFP / archmageIL / bishop / 未來其他大魔法師
// 本層只放「整個 magician branch」都共通的技能;若僅限冒險家法師三職業
// 請放 class-groups/adventurer-mage/ 下。
//
// 對外 API:
//   MAGICIAN_BRANCH_TOGGLE_SKILLS / BUFFS / VMATRIX_SKILLS / BATTLE_BUFFS / PASSIVE_SKILLS

import {
  MAGICIAN_BRANCH_0TH_TOGGLE_SKILLS, MAGICIAN_BRANCH_0TH_BUFFS, MAGICIAN_BRANCH_0TH_VMATRIX_SKILLS,
  MAGICIAN_BRANCH_0TH_BATTLE_BUFFS, MAGICIAN_BRANCH_0TH_PASSIVE_SKILLS,
} from './0th.js'
import {
  MAGICIAN_BRANCH_1ST_TOGGLE_SKILLS, MAGICIAN_BRANCH_1ST_BUFFS, MAGICIAN_BRANCH_1ST_VMATRIX_SKILLS,
  MAGICIAN_BRANCH_1ST_BATTLE_BUFFS, MAGICIAN_BRANCH_1ST_PASSIVE_SKILLS,
} from './1st.js'
import {
  MAGICIAN_BRANCH_2ND_TOGGLE_SKILLS, MAGICIAN_BRANCH_2ND_BUFFS, MAGICIAN_BRANCH_2ND_VMATRIX_SKILLS,
  MAGICIAN_BRANCH_2ND_BATTLE_BUFFS, MAGICIAN_BRANCH_2ND_PASSIVE_SKILLS,
} from './2nd.js'
import {
  MAGICIAN_BRANCH_3RD_TOGGLE_SKILLS, MAGICIAN_BRANCH_3RD_BUFFS, MAGICIAN_BRANCH_3RD_VMATRIX_SKILLS,
  MAGICIAN_BRANCH_3RD_BATTLE_BUFFS, MAGICIAN_BRANCH_3RD_PASSIVE_SKILLS,
} from './3rd.js'
import {
  MAGICIAN_BRANCH_4TH_TOGGLE_SKILLS, MAGICIAN_BRANCH_4TH_BUFFS, MAGICIAN_BRANCH_4TH_VMATRIX_SKILLS,
  MAGICIAN_BRANCH_4TH_BATTLE_BUFFS, MAGICIAN_BRANCH_4TH_PASSIVE_SKILLS,
} from './4th.js'
import {
  MAGICIAN_BRANCH_5TH_TOGGLE_SKILLS, MAGICIAN_BRANCH_5TH_BUFFS, MAGICIAN_BRANCH_5TH_VMATRIX_SKILLS,
  MAGICIAN_BRANCH_5TH_BATTLE_BUFFS, MAGICIAN_BRANCH_5TH_PASSIVE_SKILLS,
} from './5th.js'
import {
  MAGICIAN_BRANCH_6TH_TOGGLE_SKILLS, MAGICIAN_BRANCH_6TH_BUFFS, MAGICIAN_BRANCH_6TH_VMATRIX_SKILLS,
  MAGICIAN_BRANCH_6TH_BATTLE_BUFFS, MAGICIAN_BRANCH_6TH_PASSIVE_SKILLS,
} from './6th.js'

export const MAGICIAN_BRANCH_TOGGLE_SKILLS = [
  ...MAGICIAN_BRANCH_0TH_TOGGLE_SKILLS,
  ...MAGICIAN_BRANCH_1ST_TOGGLE_SKILLS,
  ...MAGICIAN_BRANCH_2ND_TOGGLE_SKILLS,
  ...MAGICIAN_BRANCH_3RD_TOGGLE_SKILLS,
  ...MAGICIAN_BRANCH_4TH_TOGGLE_SKILLS,
  ...MAGICIAN_BRANCH_5TH_TOGGLE_SKILLS,
  ...MAGICIAN_BRANCH_6TH_TOGGLE_SKILLS,
]

export const MAGICIAN_BRANCH_BUFFS = [
  ...MAGICIAN_BRANCH_0TH_BUFFS,
  ...MAGICIAN_BRANCH_1ST_BUFFS,
  ...MAGICIAN_BRANCH_2ND_BUFFS,
  ...MAGICIAN_BRANCH_3RD_BUFFS,
  ...MAGICIAN_BRANCH_4TH_BUFFS,
  ...MAGICIAN_BRANCH_5TH_BUFFS,
  ...MAGICIAN_BRANCH_6TH_BUFFS,
]

export const MAGICIAN_BRANCH_VMATRIX_SKILLS = [
  ...MAGICIAN_BRANCH_0TH_VMATRIX_SKILLS,
  ...MAGICIAN_BRANCH_1ST_VMATRIX_SKILLS,
  ...MAGICIAN_BRANCH_2ND_VMATRIX_SKILLS,
  ...MAGICIAN_BRANCH_3RD_VMATRIX_SKILLS,
  ...MAGICIAN_BRANCH_4TH_VMATRIX_SKILLS,
  ...MAGICIAN_BRANCH_5TH_VMATRIX_SKILLS,
  ...MAGICIAN_BRANCH_6TH_VMATRIX_SKILLS,
]

export const MAGICIAN_BRANCH_BATTLE_BUFFS = [
  ...MAGICIAN_BRANCH_0TH_BATTLE_BUFFS,
  ...MAGICIAN_BRANCH_1ST_BATTLE_BUFFS,
  ...MAGICIAN_BRANCH_2ND_BATTLE_BUFFS,
  ...MAGICIAN_BRANCH_3RD_BATTLE_BUFFS,
  ...MAGICIAN_BRANCH_4TH_BATTLE_BUFFS,
  ...MAGICIAN_BRANCH_5TH_BATTLE_BUFFS,
  ...MAGICIAN_BRANCH_6TH_BATTLE_BUFFS,
]

export const MAGICIAN_BRANCH_PASSIVE_SKILLS = [
  ...MAGICIAN_BRANCH_0TH_PASSIVE_SKILLS,
  ...MAGICIAN_BRANCH_1ST_PASSIVE_SKILLS,
  ...MAGICIAN_BRANCH_2ND_PASSIVE_SKILLS,
  ...MAGICIAN_BRANCH_3RD_PASSIVE_SKILLS,
  ...MAGICIAN_BRANCH_4TH_PASSIVE_SKILLS,
  ...MAGICIAN_BRANCH_5TH_PASSIVE_SKILLS,
  ...MAGICIAN_BRANCH_6TH_PASSIVE_SKILLS,
]
