// Dark Knight — 彙整 barrel

import { DARK_KNIGHT_0TH_SIM_SKILLS, DARK_KNIGHT_0TH_PASSIVE_SKILLS, DARK_KNIGHT_0TH_LINK_SKILLS } from './0th.js'
import { DARK_KNIGHT_1ST_SIM_SKILLS, DARK_KNIGHT_1ST_PASSIVE_SKILLS, DARK_KNIGHT_1ST_BUFFS, DARK_KNIGHT_1ST_BATTLE_BUFFS } from './1st.js'
import { DARK_KNIGHT_2ND_SIM_SKILLS, DARK_KNIGHT_2ND_PASSIVE_SKILLS, DARK_KNIGHT_2ND_BUFFS, DARK_KNIGHT_2ND_BATTLE_BUFFS, DARK_KNIGHT_2ND_VMATRIX_SKILLS } from './2nd.js'
import { DARK_KNIGHT_3RD_SIM_SKILLS, DARK_KNIGHT_3RD_PASSIVE_SKILLS, DARK_KNIGHT_3RD_BUFFS, DARK_KNIGHT_3RD_BATTLE_BUFFS, DARK_KNIGHT_3RD_VMATRIX_SKILLS } from './3rd.js'
import { DARK_KNIGHT_4TH_SIM_SKILLS, DARK_KNIGHT_4TH_PASSIVE_SKILLS, DARK_KNIGHT_4TH_BUFFS, DARK_KNIGHT_4TH_BATTLE_BUFFS, DARK_KNIGHT_4TH_VMATRIX_SKILLS } from './4th.js'
import { DARK_KNIGHT_5TH_SIM_SKILLS, DARK_KNIGHT_5TH_PASSIVE_SKILLS, DARK_KNIGHT_5TH_BUFFS, DARK_KNIGHT_5TH_BATTLE_BUFFS, DARK_KNIGHT_5TH_VMATRIX_SKILLS } from './5th.js'
import { DARK_KNIGHT_6TH_SIM_SKILLS, DARK_KNIGHT_6TH_PASSIVE_SKILLS, DARK_KNIGHT_6TH_BUFFS, DARK_KNIGHT_6TH_BATTLE_BUFFS, DARK_KNIGHT_6TH_VMATRIX_SKILLS } from './6th.js'
import { DARK_KNIGHT_HYPER_SKILLS, DARK_KNIGHT_HYPER_ACTIVE_SKILLS } from './hyper.js'

export const DARK_KNIGHT_SKILLS = [
  ...DARK_KNIGHT_0TH_SIM_SKILLS, ...DARK_KNIGHT_0TH_PASSIVE_SKILLS, ...DARK_KNIGHT_0TH_LINK_SKILLS,
  ...DARK_KNIGHT_1ST_SIM_SKILLS, ...DARK_KNIGHT_1ST_PASSIVE_SKILLS, ...DARK_KNIGHT_1ST_BUFFS, ...DARK_KNIGHT_1ST_BATTLE_BUFFS,
  ...DARK_KNIGHT_2ND_SIM_SKILLS, ...DARK_KNIGHT_2ND_PASSIVE_SKILLS, ...DARK_KNIGHT_2ND_BUFFS, ...DARK_KNIGHT_2ND_BATTLE_BUFFS, ...DARK_KNIGHT_2ND_VMATRIX_SKILLS,
  ...DARK_KNIGHT_3RD_SIM_SKILLS, ...DARK_KNIGHT_3RD_PASSIVE_SKILLS, ...DARK_KNIGHT_3RD_BUFFS, ...DARK_KNIGHT_3RD_BATTLE_BUFFS, ...DARK_KNIGHT_3RD_VMATRIX_SKILLS,
  ...DARK_KNIGHT_4TH_SIM_SKILLS, ...DARK_KNIGHT_4TH_PASSIVE_SKILLS, ...DARK_KNIGHT_4TH_BUFFS, ...DARK_KNIGHT_4TH_BATTLE_BUFFS, ...DARK_KNIGHT_4TH_VMATRIX_SKILLS,
  ...DARK_KNIGHT_5TH_SIM_SKILLS, ...DARK_KNIGHT_5TH_PASSIVE_SKILLS, ...DARK_KNIGHT_5TH_BUFFS, ...DARK_KNIGHT_5TH_BATTLE_BUFFS, ...DARK_KNIGHT_5TH_VMATRIX_SKILLS,
  ...DARK_KNIGHT_6TH_SIM_SKILLS, ...DARK_KNIGHT_6TH_PASSIVE_SKILLS, ...DARK_KNIGHT_6TH_BUFFS, ...DARK_KNIGHT_6TH_BATTLE_BUFFS, ...DARK_KNIGHT_6TH_VMATRIX_SKILLS,
  ...DARK_KNIGHT_HYPER_SKILLS,
  ...DARK_KNIGHT_HYPER_ACTIVE_SKILLS,
]

export const DARK_KNIGHT_SIM_SKILLS = [
  ...DARK_KNIGHT_0TH_SIM_SKILLS,
  ...DARK_KNIGHT_1ST_SIM_SKILLS,
  ...DARK_KNIGHT_2ND_SIM_SKILLS,
  ...DARK_KNIGHT_3RD_SIM_SKILLS,
  ...DARK_KNIGHT_4TH_SIM_SKILLS,
  ...DARK_KNIGHT_5TH_SIM_SKILLS,
  ...DARK_KNIGHT_6TH_SIM_SKILLS,
]

export const DARK_KNIGHT_PASSIVE_SKILLS = [
  ...DARK_KNIGHT_0TH_PASSIVE_SKILLS,
  ...DARK_KNIGHT_1ST_PASSIVE_SKILLS,
  ...DARK_KNIGHT_2ND_PASSIVE_SKILLS,
  ...DARK_KNIGHT_3RD_PASSIVE_SKILLS,
  ...DARK_KNIGHT_4TH_PASSIVE_SKILLS,
  ...DARK_KNIGHT_5TH_PASSIVE_SKILLS,
  ...DARK_KNIGHT_6TH_PASSIVE_SKILLS,
  ...DARK_KNIGHT_HYPER_ACTIVE_SKILLS.filter((s) => s.cp?.role === 'passive'),
]

export const DARK_KNIGHT_BUFFS = [
  ...DARK_KNIGHT_1ST_BUFFS,
  ...DARK_KNIGHT_2ND_BUFFS,
  ...DARK_KNIGHT_3RD_BUFFS,
  ...DARK_KNIGHT_4TH_BUFFS,
  ...DARK_KNIGHT_5TH_BUFFS,
  ...DARK_KNIGHT_6TH_BUFFS,
]

export const DARK_KNIGHT_BATTLE_BUFFS = [
  ...DARK_KNIGHT_1ST_BATTLE_BUFFS,
  ...DARK_KNIGHT_2ND_BATTLE_BUFFS,
  ...DARK_KNIGHT_3RD_BATTLE_BUFFS,
  ...DARK_KNIGHT_4TH_BATTLE_BUFFS,
  ...DARK_KNIGHT_5TH_BATTLE_BUFFS,
  ...DARK_KNIGHT_6TH_BATTLE_BUFFS,
]

export const DARK_KNIGHT_VMATRIX_SKILLS = [
  ...DARK_KNIGHT_2ND_VMATRIX_SKILLS,
  ...DARK_KNIGHT_3RD_VMATRIX_SKILLS,
  ...DARK_KNIGHT_4TH_VMATRIX_SKILLS,
  ...DARK_KNIGHT_5TH_VMATRIX_SKILLS,
  ...DARK_KNIGHT_6TH_VMATRIX_SKILLS,
]

export const DARK_KNIGHT_HYPER_SKILLS_ALL = DARK_KNIGHT_HYPER_SKILLS

export const DARK_KNIGHT_LINK_SKILLS = DARK_KNIGHT_0TH_LINK_SKILLS
