// Bishop — 彙整 barrel

import { BISHOP_0TH_SIM_SKILLS, BISHOP_0TH_PASSIVE_SKILLS, BISHOP_0TH_LINK_SKILLS } from './0th.js'
import { BISHOP_1ST_SIM_SKILLS, BISHOP_1ST_PASSIVE_SKILLS, BISHOP_1ST_BUFFS, BISHOP_1ST_BATTLE_BUFFS } from './1st.js'
import { BISHOP_2ND_SIM_SKILLS, BISHOP_2ND_PASSIVE_SKILLS, BISHOP_2ND_BUFFS, BISHOP_2ND_BATTLE_BUFFS, BISHOP_2ND_VMATRIX_SKILLS } from './2nd.js'
import { BISHOP_3RD_SIM_SKILLS, BISHOP_3RD_PASSIVE_SKILLS, BISHOP_3RD_BUFFS, BISHOP_3RD_BATTLE_BUFFS, BISHOP_3RD_VMATRIX_SKILLS } from './3rd.js'
import { BISHOP_4TH_SIM_SKILLS, BISHOP_4TH_PASSIVE_SKILLS, BISHOP_4TH_BUFFS, BISHOP_4TH_BATTLE_BUFFS, BISHOP_4TH_VMATRIX_SKILLS } from './4th.js'
import { BISHOP_5TH_SIM_SKILLS, BISHOP_5TH_PASSIVE_SKILLS, BISHOP_5TH_BUFFS, BISHOP_5TH_BATTLE_BUFFS, BISHOP_5TH_VMATRIX_SKILLS } from './5th.js'
import { BISHOP_6TH_SIM_SKILLS, BISHOP_6TH_PASSIVE_SKILLS, BISHOP_6TH_BUFFS, BISHOP_6TH_BATTLE_BUFFS, BISHOP_6TH_VMATRIX_SKILLS } from './6th.js'
import { BISHOP_HYPER_SKILLS, BISHOP_HYPER_ACTIVE_SKILLS } from './hyper.js'

export const BISHOP_SKILLS = [
  ...BISHOP_0TH_SIM_SKILLS, ...BISHOP_0TH_PASSIVE_SKILLS, ...BISHOP_0TH_LINK_SKILLS,
  ...BISHOP_1ST_SIM_SKILLS, ...BISHOP_1ST_PASSIVE_SKILLS, ...BISHOP_1ST_BUFFS, ...BISHOP_1ST_BATTLE_BUFFS,
  ...BISHOP_2ND_SIM_SKILLS, ...BISHOP_2ND_PASSIVE_SKILLS, ...BISHOP_2ND_BUFFS, ...BISHOP_2ND_BATTLE_BUFFS, ...BISHOP_2ND_VMATRIX_SKILLS,
  ...BISHOP_3RD_SIM_SKILLS, ...BISHOP_3RD_PASSIVE_SKILLS, ...BISHOP_3RD_BUFFS, ...BISHOP_3RD_BATTLE_BUFFS, ...BISHOP_3RD_VMATRIX_SKILLS,
  ...BISHOP_4TH_SIM_SKILLS, ...BISHOP_4TH_PASSIVE_SKILLS, ...BISHOP_4TH_BUFFS, ...BISHOP_4TH_BATTLE_BUFFS, ...BISHOP_4TH_VMATRIX_SKILLS,
  ...BISHOP_5TH_SIM_SKILLS, ...BISHOP_5TH_PASSIVE_SKILLS, ...BISHOP_5TH_BUFFS, ...BISHOP_5TH_BATTLE_BUFFS, ...BISHOP_5TH_VMATRIX_SKILLS,
  ...BISHOP_6TH_SIM_SKILLS, ...BISHOP_6TH_PASSIVE_SKILLS, ...BISHOP_6TH_BUFFS, ...BISHOP_6TH_BATTLE_BUFFS, ...BISHOP_6TH_VMATRIX_SKILLS,
  ...BISHOP_HYPER_SKILLS,
  ...BISHOP_HYPER_ACTIVE_SKILLS,
]

export const BISHOP_SIM_SKILLS = [
  ...BISHOP_0TH_SIM_SKILLS,
  ...BISHOP_1ST_SIM_SKILLS,
  ...BISHOP_2ND_SIM_SKILLS,
  ...BISHOP_3RD_SIM_SKILLS,
  ...BISHOP_4TH_SIM_SKILLS,
  ...BISHOP_5TH_SIM_SKILLS,
  ...BISHOP_6TH_SIM_SKILLS,
]

export const BISHOP_PASSIVE_SKILLS = [
  ...BISHOP_0TH_PASSIVE_SKILLS,
  ...BISHOP_1ST_PASSIVE_SKILLS,
  ...BISHOP_2ND_PASSIVE_SKILLS,
  ...BISHOP_3RD_PASSIVE_SKILLS,
  ...BISHOP_4TH_PASSIVE_SKILLS,
  ...BISHOP_5TH_PASSIVE_SKILLS,
  ...BISHOP_6TH_PASSIVE_SKILLS,
  ...BISHOP_HYPER_ACTIVE_SKILLS.filter((s) => s.cp?.role === 'passive'),
]

export const BISHOP_BUFFS = [
  ...BISHOP_1ST_BUFFS,
  ...BISHOP_2ND_BUFFS,
  ...BISHOP_3RD_BUFFS,
  ...BISHOP_4TH_BUFFS,
  ...BISHOP_5TH_BUFFS,
  ...BISHOP_6TH_BUFFS,
]

export const BISHOP_BATTLE_BUFFS = [
  ...BISHOP_1ST_BATTLE_BUFFS,
  ...BISHOP_2ND_BATTLE_BUFFS,
  ...BISHOP_3RD_BATTLE_BUFFS,
  ...BISHOP_4TH_BATTLE_BUFFS,
  ...BISHOP_5TH_BATTLE_BUFFS,
  ...BISHOP_6TH_BATTLE_BUFFS,
]

export const BISHOP_VMATRIX_SKILLS = [
  ...BISHOP_2ND_VMATRIX_SKILLS,
  ...BISHOP_3RD_VMATRIX_SKILLS,
  ...BISHOP_4TH_VMATRIX_SKILLS,
  ...BISHOP_5TH_VMATRIX_SKILLS,
  ...BISHOP_6TH_VMATRIX_SKILLS,
]

export const BISHOP_HYPER_SKILLS_ALL = BISHOP_HYPER_SKILLS

export const BISHOP_LINK_SKILLS = BISHOP_0TH_LINK_SKILLS
