// Night Walker — 彙整 barrel

import { NIGHT_WALKER_0TH_SIM_SKILLS, NIGHT_WALKER_0TH_PASSIVE_SKILLS, NIGHT_WALKER_0TH_LINK_SKILLS } from './0th.js'
import { NIGHT_WALKER_1ST_SIM_SKILLS, NIGHT_WALKER_1ST_PASSIVE_SKILLS, NIGHT_WALKER_1ST_BUFFS, NIGHT_WALKER_1ST_BATTLE_BUFFS } from './1st.js'
import { NIGHT_WALKER_2ND_SIM_SKILLS, NIGHT_WALKER_2ND_PASSIVE_SKILLS, NIGHT_WALKER_2ND_BUFFS, NIGHT_WALKER_2ND_BATTLE_BUFFS, NIGHT_WALKER_2ND_VMATRIX_SKILLS } from './2nd.js'
import { NIGHT_WALKER_3RD_SIM_SKILLS, NIGHT_WALKER_3RD_PASSIVE_SKILLS, NIGHT_WALKER_3RD_BUFFS, NIGHT_WALKER_3RD_BATTLE_BUFFS, NIGHT_WALKER_3RD_VMATRIX_SKILLS } from './3rd.js'
import { NIGHT_WALKER_4TH_SIM_SKILLS, NIGHT_WALKER_4TH_PASSIVE_SKILLS, NIGHT_WALKER_4TH_BUFFS, NIGHT_WALKER_4TH_BATTLE_BUFFS, NIGHT_WALKER_4TH_VMATRIX_SKILLS } from './4th.js'
import { NIGHT_WALKER_5TH_SIM_SKILLS, NIGHT_WALKER_5TH_PASSIVE_SKILLS, NIGHT_WALKER_5TH_BUFFS, NIGHT_WALKER_5TH_BATTLE_BUFFS, NIGHT_WALKER_5TH_VMATRIX_SKILLS } from './5th.js'
import { NIGHT_WALKER_6TH_SIM_SKILLS, NIGHT_WALKER_6TH_PASSIVE_SKILLS, NIGHT_WALKER_6TH_BUFFS, NIGHT_WALKER_6TH_BATTLE_BUFFS, NIGHT_WALKER_6TH_VMATRIX_SKILLS } from './6th.js'
import { NIGHT_WALKER_HYPER_SKILLS, NIGHT_WALKER_HYPER_ACTIVE_SKILLS } from './hyper.js'

export const NIGHT_WALKER_SKILLS = [
  ...NIGHT_WALKER_0TH_SIM_SKILLS, ...NIGHT_WALKER_0TH_PASSIVE_SKILLS, ...NIGHT_WALKER_0TH_LINK_SKILLS,
  ...NIGHT_WALKER_1ST_SIM_SKILLS, ...NIGHT_WALKER_1ST_PASSIVE_SKILLS, ...NIGHT_WALKER_1ST_BUFFS, ...NIGHT_WALKER_1ST_BATTLE_BUFFS,
  ...NIGHT_WALKER_2ND_SIM_SKILLS, ...NIGHT_WALKER_2ND_PASSIVE_SKILLS, ...NIGHT_WALKER_2ND_BUFFS, ...NIGHT_WALKER_2ND_BATTLE_BUFFS, ...NIGHT_WALKER_2ND_VMATRIX_SKILLS,
  ...NIGHT_WALKER_3RD_SIM_SKILLS, ...NIGHT_WALKER_3RD_PASSIVE_SKILLS, ...NIGHT_WALKER_3RD_BUFFS, ...NIGHT_WALKER_3RD_BATTLE_BUFFS, ...NIGHT_WALKER_3RD_VMATRIX_SKILLS,
  ...NIGHT_WALKER_4TH_SIM_SKILLS, ...NIGHT_WALKER_4TH_PASSIVE_SKILLS, ...NIGHT_WALKER_4TH_BUFFS, ...NIGHT_WALKER_4TH_BATTLE_BUFFS, ...NIGHT_WALKER_4TH_VMATRIX_SKILLS,
  ...NIGHT_WALKER_5TH_SIM_SKILLS, ...NIGHT_WALKER_5TH_PASSIVE_SKILLS, ...NIGHT_WALKER_5TH_BUFFS, ...NIGHT_WALKER_5TH_BATTLE_BUFFS, ...NIGHT_WALKER_5TH_VMATRIX_SKILLS,
  ...NIGHT_WALKER_6TH_SIM_SKILLS, ...NIGHT_WALKER_6TH_PASSIVE_SKILLS, ...NIGHT_WALKER_6TH_BUFFS, ...NIGHT_WALKER_6TH_BATTLE_BUFFS, ...NIGHT_WALKER_6TH_VMATRIX_SKILLS,
  ...NIGHT_WALKER_HYPER_SKILLS,
  ...NIGHT_WALKER_HYPER_ACTIVE_SKILLS,
]

export const NIGHT_WALKER_SIM_SKILLS = [
  ...NIGHT_WALKER_0TH_SIM_SKILLS,
  ...NIGHT_WALKER_1ST_SIM_SKILLS,
  ...NIGHT_WALKER_2ND_SIM_SKILLS,
  ...NIGHT_WALKER_3RD_SIM_SKILLS,
  ...NIGHT_WALKER_4TH_SIM_SKILLS,
  ...NIGHT_WALKER_5TH_SIM_SKILLS,
  ...NIGHT_WALKER_6TH_SIM_SKILLS,
]

export const NIGHT_WALKER_PASSIVE_SKILLS = [
  ...NIGHT_WALKER_0TH_PASSIVE_SKILLS,
  ...NIGHT_WALKER_1ST_PASSIVE_SKILLS,
  ...NIGHT_WALKER_2ND_PASSIVE_SKILLS,
  ...NIGHT_WALKER_3RD_PASSIVE_SKILLS,
  ...NIGHT_WALKER_4TH_PASSIVE_SKILLS,
  ...NIGHT_WALKER_5TH_PASSIVE_SKILLS,
  ...NIGHT_WALKER_6TH_PASSIVE_SKILLS,
  ...NIGHT_WALKER_HYPER_ACTIVE_SKILLS.filter((s) => s.cp?.role === 'passive'),
]

export const NIGHT_WALKER_BUFFS = [
  ...NIGHT_WALKER_1ST_BUFFS,
  ...NIGHT_WALKER_2ND_BUFFS,
  ...NIGHT_WALKER_3RD_BUFFS,
  ...NIGHT_WALKER_4TH_BUFFS,
  ...NIGHT_WALKER_5TH_BUFFS,
  ...NIGHT_WALKER_6TH_BUFFS,
]

export const NIGHT_WALKER_BATTLE_BUFFS = [
  ...NIGHT_WALKER_1ST_BATTLE_BUFFS,
  ...NIGHT_WALKER_2ND_BATTLE_BUFFS,
  ...NIGHT_WALKER_3RD_BATTLE_BUFFS,
  ...NIGHT_WALKER_4TH_BATTLE_BUFFS,
  ...NIGHT_WALKER_5TH_BATTLE_BUFFS,
  ...NIGHT_WALKER_6TH_BATTLE_BUFFS,
]

export const NIGHT_WALKER_VMATRIX_SKILLS = [
  ...NIGHT_WALKER_2ND_VMATRIX_SKILLS,
  ...NIGHT_WALKER_3RD_VMATRIX_SKILLS,
  ...NIGHT_WALKER_4TH_VMATRIX_SKILLS,
  ...NIGHT_WALKER_5TH_VMATRIX_SKILLS,
  ...NIGHT_WALKER_6TH_VMATRIX_SKILLS,
]

export const NIGHT_WALKER_HYPER_SKILLS_ALL = NIGHT_WALKER_HYPER_SKILLS

export const NIGHT_WALKER_LINK_SKILLS = NIGHT_WALKER_0TH_LINK_SKILLS
