// Luminous — 彙整 barrel

import { LUMINOUS_0TH_SIM_SKILLS, LUMINOUS_0TH_PASSIVE_SKILLS, LUMINOUS_0TH_LINK_SKILLS, LUMINOUS_0TH_TOGGLE_SKILLS } from './0th.js'
import { LUMINOUS_1ST_SIM_SKILLS, LUMINOUS_1ST_PASSIVE_SKILLS, LUMINOUS_1ST_BUFFS, LUMINOUS_1ST_BATTLE_BUFFS } from './1st.js'
import { LUMINOUS_2ND_SIM_SKILLS, LUMINOUS_2ND_PASSIVE_SKILLS, LUMINOUS_2ND_BUFFS, LUMINOUS_2ND_BATTLE_BUFFS, LUMINOUS_2ND_VMATRIX_SKILLS } from './2nd.js'
import { LUMINOUS_3RD_SIM_SKILLS, LUMINOUS_3RD_PASSIVE_SKILLS, LUMINOUS_3RD_BUFFS, LUMINOUS_3RD_BATTLE_BUFFS, LUMINOUS_3RD_VMATRIX_SKILLS } from './3rd.js'
import { LUMINOUS_4TH_SIM_SKILLS, LUMINOUS_4TH_PASSIVE_SKILLS, LUMINOUS_4TH_BUFFS, LUMINOUS_4TH_BATTLE_BUFFS, LUMINOUS_4TH_VMATRIX_SKILLS } from './4th.js'
import { LUMINOUS_5TH_SIM_SKILLS, LUMINOUS_5TH_PASSIVE_SKILLS, LUMINOUS_5TH_BUFFS, LUMINOUS_5TH_BATTLE_BUFFS, LUMINOUS_5TH_VMATRIX_SKILLS } from './5th.js'
import { LUMINOUS_6TH_SIM_SKILLS, LUMINOUS_6TH_PASSIVE_SKILLS, LUMINOUS_6TH_BUFFS, LUMINOUS_6TH_BATTLE_BUFFS, LUMINOUS_6TH_VMATRIX_SKILLS } from './6th.js'
import { LUMINOUS_HYPER_SKILLS, LUMINOUS_HYPER_ACTIVE_SKILLS } from './hyper.js'
export { LUMINOUS_MECHANICS } from './mechanics.js'

export const LUMINOUS_SKILLS = [
  ...LUMINOUS_0TH_SIM_SKILLS, ...LUMINOUS_0TH_PASSIVE_SKILLS, ...LUMINOUS_0TH_LINK_SKILLS, ...LUMINOUS_0TH_TOGGLE_SKILLS,
  ...LUMINOUS_1ST_SIM_SKILLS, ...LUMINOUS_1ST_PASSIVE_SKILLS, ...LUMINOUS_1ST_BUFFS, ...LUMINOUS_1ST_BATTLE_BUFFS,
  ...LUMINOUS_2ND_SIM_SKILLS, ...LUMINOUS_2ND_PASSIVE_SKILLS, ...LUMINOUS_2ND_BUFFS, ...LUMINOUS_2ND_BATTLE_BUFFS, ...LUMINOUS_2ND_VMATRIX_SKILLS,
  ...LUMINOUS_3RD_SIM_SKILLS, ...LUMINOUS_3RD_PASSIVE_SKILLS, ...LUMINOUS_3RD_BUFFS, ...LUMINOUS_3RD_BATTLE_BUFFS, ...LUMINOUS_3RD_VMATRIX_SKILLS,
  ...LUMINOUS_4TH_SIM_SKILLS, ...LUMINOUS_4TH_PASSIVE_SKILLS, ...LUMINOUS_4TH_BUFFS, ...LUMINOUS_4TH_BATTLE_BUFFS, ...LUMINOUS_4TH_VMATRIX_SKILLS,
  ...LUMINOUS_5TH_SIM_SKILLS, ...LUMINOUS_5TH_PASSIVE_SKILLS, ...LUMINOUS_5TH_BUFFS, ...LUMINOUS_5TH_BATTLE_BUFFS, ...LUMINOUS_5TH_VMATRIX_SKILLS,
  ...LUMINOUS_6TH_SIM_SKILLS, ...LUMINOUS_6TH_PASSIVE_SKILLS, ...LUMINOUS_6TH_BUFFS, ...LUMINOUS_6TH_BATTLE_BUFFS, ...LUMINOUS_6TH_VMATRIX_SKILLS,
  ...LUMINOUS_HYPER_SKILLS,
  ...LUMINOUS_HYPER_ACTIVE_SKILLS,
]

export const LUMINOUS_SIM_SKILLS = [
  ...LUMINOUS_0TH_SIM_SKILLS,
  ...LUMINOUS_1ST_SIM_SKILLS,
  ...LUMINOUS_2ND_SIM_SKILLS,
  ...LUMINOUS_3RD_SIM_SKILLS,
  ...LUMINOUS_4TH_SIM_SKILLS,
  ...LUMINOUS_5TH_SIM_SKILLS,
  ...LUMINOUS_6TH_SIM_SKILLS,
  ...LUMINOUS_HYPER_ACTIVE_SKILLS.filter((s) => s.sim),
]

export const LUMINOUS_PASSIVE_SKILLS = [
  ...LUMINOUS_0TH_PASSIVE_SKILLS,
  ...LUMINOUS_1ST_PASSIVE_SKILLS,
  ...LUMINOUS_2ND_PASSIVE_SKILLS,
  ...LUMINOUS_3RD_PASSIVE_SKILLS,
  ...LUMINOUS_4TH_PASSIVE_SKILLS,
  ...LUMINOUS_5TH_PASSIVE_SKILLS,
  ...LUMINOUS_6TH_PASSIVE_SKILLS,
  ...LUMINOUS_HYPER_ACTIVE_SKILLS.filter((s) => s.cp?.role === 'passive'),
]

export const LUMINOUS_BUFFS = [
  ...LUMINOUS_1ST_BUFFS,
  ...LUMINOUS_2ND_BUFFS,
  ...LUMINOUS_3RD_BUFFS,
  ...LUMINOUS_4TH_BUFFS,
  ...LUMINOUS_5TH_BUFFS,
  ...LUMINOUS_6TH_BUFFS,
  ...LUMINOUS_HYPER_ACTIVE_SKILLS.filter((s) => s.cp?.role === 'buff'),
]

export const LUMINOUS_BATTLE_BUFFS = [
  ...LUMINOUS_1ST_BATTLE_BUFFS,
  ...LUMINOUS_2ND_BATTLE_BUFFS,
  ...LUMINOUS_3RD_BATTLE_BUFFS,
  ...LUMINOUS_4TH_BATTLE_BUFFS,
  ...LUMINOUS_5TH_BATTLE_BUFFS,
  ...LUMINOUS_6TH_BATTLE_BUFFS,
  ...LUMINOUS_HYPER_ACTIVE_SKILLS.filter((s) => s.battle).map((s) => ({
    id: s.id,
    nameKey: s.nameKey,
    descriptionKey: s.descriptionKey,
    imageUrl: s.imageUrl,
    jobs: s.jobs,
    advancement: s.advancement,
    kind: s.kind,
    baseLevel: s.baseLevel,
    ...s.battle,
  })),
]

export const LUMINOUS_VMATRIX_SKILLS = [
  ...LUMINOUS_2ND_VMATRIX_SKILLS,
  ...LUMINOUS_3RD_VMATRIX_SKILLS,
  ...LUMINOUS_4TH_VMATRIX_SKILLS,
  ...LUMINOUS_5TH_VMATRIX_SKILLS,
  ...LUMINOUS_6TH_VMATRIX_SKILLS,
]

export const LUMINOUS_HYPER_SKILLS_ALL = LUMINOUS_HYPER_SKILLS

export const LUMINOUS_LINK_SKILLS = LUMINOUS_0TH_LINK_SKILLS

export const LUMINOUS_TOGGLE_SKILLS = LUMINOUS_0TH_TOGGLE_SKILLS
