// Buccaneer — 彙整 barrel

import { BUCCANEER_0TH_SIM_SKILLS, BUCCANEER_0TH_PASSIVE_SKILLS, BUCCANEER_0TH_LINK_SKILLS } from './0th.js'
import { BUCCANEER_1ST_SIM_SKILLS, BUCCANEER_1ST_PASSIVE_SKILLS, BUCCANEER_1ST_BUFFS, BUCCANEER_1ST_BATTLE_BUFFS } from './1st.js'
import { BUCCANEER_2ND_SIM_SKILLS, BUCCANEER_2ND_PASSIVE_SKILLS, BUCCANEER_2ND_BUFFS, BUCCANEER_2ND_BATTLE_BUFFS, BUCCANEER_2ND_VMATRIX_SKILLS } from './2nd.js'
import { BUCCANEER_3RD_SIM_SKILLS, BUCCANEER_3RD_PASSIVE_SKILLS, BUCCANEER_3RD_BUFFS, BUCCANEER_3RD_BATTLE_BUFFS, BUCCANEER_3RD_VMATRIX_SKILLS } from './3rd.js'
import { BUCCANEER_4TH_SIM_SKILLS, BUCCANEER_4TH_PASSIVE_SKILLS, BUCCANEER_4TH_BUFFS, BUCCANEER_4TH_BATTLE_BUFFS, BUCCANEER_4TH_VMATRIX_SKILLS } from './4th.js'
import { BUCCANEER_5TH_SIM_SKILLS, BUCCANEER_5TH_PASSIVE_SKILLS, BUCCANEER_5TH_BUFFS, BUCCANEER_5TH_BATTLE_BUFFS, BUCCANEER_5TH_VMATRIX_SKILLS } from './5th.js'
import { BUCCANEER_6TH_SIM_SKILLS, BUCCANEER_6TH_PASSIVE_SKILLS, BUCCANEER_6TH_BUFFS, BUCCANEER_6TH_BATTLE_BUFFS, BUCCANEER_6TH_VMATRIX_SKILLS } from './6th.js'
import { BUCCANEER_HYPER_SKILLS, BUCCANEER_HYPER_ACTIVE_SKILLS } from './hyper.js'

export const BUCCANEER_SKILLS = [
  ...BUCCANEER_0TH_SIM_SKILLS, ...BUCCANEER_0TH_PASSIVE_SKILLS, ...BUCCANEER_0TH_LINK_SKILLS,
  ...BUCCANEER_1ST_SIM_SKILLS, ...BUCCANEER_1ST_PASSIVE_SKILLS, ...BUCCANEER_1ST_BUFFS, ...BUCCANEER_1ST_BATTLE_BUFFS,
  ...BUCCANEER_2ND_SIM_SKILLS, ...BUCCANEER_2ND_PASSIVE_SKILLS, ...BUCCANEER_2ND_BUFFS, ...BUCCANEER_2ND_BATTLE_BUFFS, ...BUCCANEER_2ND_VMATRIX_SKILLS,
  ...BUCCANEER_3RD_SIM_SKILLS, ...BUCCANEER_3RD_PASSIVE_SKILLS, ...BUCCANEER_3RD_BUFFS, ...BUCCANEER_3RD_BATTLE_BUFFS, ...BUCCANEER_3RD_VMATRIX_SKILLS,
  ...BUCCANEER_4TH_SIM_SKILLS, ...BUCCANEER_4TH_PASSIVE_SKILLS, ...BUCCANEER_4TH_BUFFS, ...BUCCANEER_4TH_BATTLE_BUFFS, ...BUCCANEER_4TH_VMATRIX_SKILLS,
  ...BUCCANEER_5TH_SIM_SKILLS, ...BUCCANEER_5TH_PASSIVE_SKILLS, ...BUCCANEER_5TH_BUFFS, ...BUCCANEER_5TH_BATTLE_BUFFS, ...BUCCANEER_5TH_VMATRIX_SKILLS,
  ...BUCCANEER_6TH_SIM_SKILLS, ...BUCCANEER_6TH_PASSIVE_SKILLS, ...BUCCANEER_6TH_BUFFS, ...BUCCANEER_6TH_BATTLE_BUFFS, ...BUCCANEER_6TH_VMATRIX_SKILLS,
  ...BUCCANEER_HYPER_SKILLS,
  ...BUCCANEER_HYPER_ACTIVE_SKILLS,
]

export const BUCCANEER_SIM_SKILLS = [
  ...BUCCANEER_0TH_SIM_SKILLS,
  ...BUCCANEER_1ST_SIM_SKILLS,
  ...BUCCANEER_2ND_SIM_SKILLS,
  ...BUCCANEER_3RD_SIM_SKILLS,
  ...BUCCANEER_4TH_SIM_SKILLS,
  ...BUCCANEER_5TH_SIM_SKILLS,
  ...BUCCANEER_6TH_SIM_SKILLS,
]

export const BUCCANEER_PASSIVE_SKILLS = [
  ...BUCCANEER_0TH_PASSIVE_SKILLS,
  ...BUCCANEER_1ST_PASSIVE_SKILLS,
  ...BUCCANEER_2ND_PASSIVE_SKILLS,
  ...BUCCANEER_3RD_PASSIVE_SKILLS,
  ...BUCCANEER_4TH_PASSIVE_SKILLS,
  ...BUCCANEER_5TH_PASSIVE_SKILLS,
  ...BUCCANEER_6TH_PASSIVE_SKILLS,
  ...BUCCANEER_HYPER_ACTIVE_SKILLS.filter((s) => s.cp?.role === 'passive'),
]

export const BUCCANEER_BUFFS = [
  ...BUCCANEER_1ST_BUFFS,
  ...BUCCANEER_2ND_BUFFS,
  ...BUCCANEER_3RD_BUFFS,
  ...BUCCANEER_4TH_BUFFS,
  ...BUCCANEER_5TH_BUFFS,
  ...BUCCANEER_6TH_BUFFS,
]

export const BUCCANEER_BATTLE_BUFFS = [
  ...BUCCANEER_1ST_BATTLE_BUFFS,
  ...BUCCANEER_2ND_BATTLE_BUFFS,
  ...BUCCANEER_3RD_BATTLE_BUFFS,
  ...BUCCANEER_4TH_BATTLE_BUFFS,
  ...BUCCANEER_5TH_BATTLE_BUFFS,
  ...BUCCANEER_6TH_BATTLE_BUFFS,
]

export const BUCCANEER_VMATRIX_SKILLS = [
  ...BUCCANEER_2ND_VMATRIX_SKILLS,
  ...BUCCANEER_3RD_VMATRIX_SKILLS,
  ...BUCCANEER_4TH_VMATRIX_SKILLS,
  ...BUCCANEER_5TH_VMATRIX_SKILLS,
  ...BUCCANEER_6TH_VMATRIX_SKILLS,
]

export const BUCCANEER_HYPER_SKILLS_ALL = BUCCANEER_HYPER_SKILLS

export const BUCCANEER_LINK_SKILLS = BUCCANEER_0TH_LINK_SKILLS
