// 冒險家法師共通 barrel — 彙整 0~6 轉
// 對外 API 沿用舊命名:
//   ADVENTURER_MAGE_PASSIVE_SKILLS
//   ADVENTURER_MAGE_BATTLE_BUFFS
//   ADVENTURER_MAGE_VMATRIX_SKILLS
// 以及新增 TOGGLE / BUFFS 類型(目前多為空陣列)

import {
  ADVENTURER_MAGE_0TH_TOGGLE_SKILLS, ADVENTURER_MAGE_0TH_BUFFS, ADVENTURER_MAGE_0TH_VMATRIX_SKILLS,
  ADVENTURER_MAGE_0TH_BATTLE_BUFFS, ADVENTURER_MAGE_0TH_PASSIVE_SKILLS,
} from './0th.js'
import {
  ADVENTURER_MAGE_1ST_TOGGLE_SKILLS, ADVENTURER_MAGE_1ST_BUFFS, ADVENTURER_MAGE_1ST_VMATRIX_SKILLS,
  ADVENTURER_MAGE_1ST_BATTLE_BUFFS, ADVENTURER_MAGE_1ST_PASSIVE_SKILLS,
} from './1st.js'
import {
  ADVENTURER_MAGE_2ND_TOGGLE_SKILLS, ADVENTURER_MAGE_2ND_BUFFS, ADVENTURER_MAGE_2ND_VMATRIX_SKILLS,
  ADVENTURER_MAGE_2ND_BATTLE_BUFFS, ADVENTURER_MAGE_2ND_PASSIVE_SKILLS,
} from './2nd.js'
import {
  ADVENTURER_MAGE_3RD_TOGGLE_SKILLS, ADVENTURER_MAGE_3RD_BUFFS, ADVENTURER_MAGE_3RD_VMATRIX_SKILLS,
  ADVENTURER_MAGE_3RD_BATTLE_BUFFS, ADVENTURER_MAGE_3RD_PASSIVE_SKILLS,
} from './3rd.js'
import {
  ADVENTURER_MAGE_4TH_TOGGLE_SKILLS, ADVENTURER_MAGE_4TH_BUFFS, ADVENTURER_MAGE_4TH_VMATRIX_SKILLS,
  ADVENTURER_MAGE_4TH_BATTLE_BUFFS, ADVENTURER_MAGE_4TH_PASSIVE_SKILLS,
} from './4th.js'
import {
  ADVENTURER_MAGE_5TH_TOGGLE_SKILLS, ADVENTURER_MAGE_5TH_BUFFS, ADVENTURER_MAGE_5TH_VMATRIX_SKILLS,
  ADVENTURER_MAGE_5TH_BATTLE_BUFFS, ADVENTURER_MAGE_5TH_PASSIVE_SKILLS,
} from './5th.js'
import {
  ADVENTURER_MAGE_6TH_TOGGLE_SKILLS, ADVENTURER_MAGE_6TH_BUFFS, ADVENTURER_MAGE_6TH_VMATRIX_SKILLS,
  ADVENTURER_MAGE_6TH_BATTLE_BUFFS, ADVENTURER_MAGE_6TH_PASSIVE_SKILLS,
} from './6th.js'

export const ADVENTURER_MAGE_TOGGLE_SKILLS = [
  ...ADVENTURER_MAGE_0TH_TOGGLE_SKILLS,
  ...ADVENTURER_MAGE_1ST_TOGGLE_SKILLS,
  ...ADVENTURER_MAGE_2ND_TOGGLE_SKILLS,
  ...ADVENTURER_MAGE_3RD_TOGGLE_SKILLS,
  ...ADVENTURER_MAGE_4TH_TOGGLE_SKILLS,
  ...ADVENTURER_MAGE_5TH_TOGGLE_SKILLS,
  ...ADVENTURER_MAGE_6TH_TOGGLE_SKILLS,
]

export const ADVENTURER_MAGE_BUFFS = [
  ...ADVENTURER_MAGE_0TH_BUFFS,
  ...ADVENTURER_MAGE_1ST_BUFFS,
  ...ADVENTURER_MAGE_2ND_BUFFS,
  ...ADVENTURER_MAGE_3RD_BUFFS,
  ...ADVENTURER_MAGE_4TH_BUFFS,
  ...ADVENTURER_MAGE_5TH_BUFFS,
  ...ADVENTURER_MAGE_6TH_BUFFS,
]

export const ADVENTURER_MAGE_VMATRIX_SKILLS = [
  ...ADVENTURER_MAGE_0TH_VMATRIX_SKILLS,
  ...ADVENTURER_MAGE_1ST_VMATRIX_SKILLS,
  ...ADVENTURER_MAGE_2ND_VMATRIX_SKILLS,
  ...ADVENTURER_MAGE_3RD_VMATRIX_SKILLS,
  ...ADVENTURER_MAGE_4TH_VMATRIX_SKILLS,
  ...ADVENTURER_MAGE_5TH_VMATRIX_SKILLS,
  ...ADVENTURER_MAGE_6TH_VMATRIX_SKILLS,
]

export const ADVENTURER_MAGE_BATTLE_BUFFS = [
  ...ADVENTURER_MAGE_0TH_BATTLE_BUFFS,
  ...ADVENTURER_MAGE_1ST_BATTLE_BUFFS,
  ...ADVENTURER_MAGE_2ND_BATTLE_BUFFS,
  ...ADVENTURER_MAGE_3RD_BATTLE_BUFFS,
  ...ADVENTURER_MAGE_4TH_BATTLE_BUFFS,
  ...ADVENTURER_MAGE_5TH_BATTLE_BUFFS,
  ...ADVENTURER_MAGE_6TH_BATTLE_BUFFS,
]

export const ADVENTURER_MAGE_PASSIVE_SKILLS = [
  ...ADVENTURER_MAGE_0TH_PASSIVE_SKILLS,
  ...ADVENTURER_MAGE_1ST_PASSIVE_SKILLS,
  ...ADVENTURER_MAGE_2ND_PASSIVE_SKILLS,
  ...ADVENTURER_MAGE_3RD_PASSIVE_SKILLS,
  ...ADVENTURER_MAGE_4TH_PASSIVE_SKILLS,
  ...ADVENTURER_MAGE_5TH_PASSIVE_SKILLS,
  ...ADVENTURER_MAGE_6TH_PASSIVE_SKILLS,
]
