// Wind Archer — 彙整 barrel

import { WIND_ARCHER_0TH_SIM_SKILLS, WIND_ARCHER_0TH_PASSIVE_SKILLS, WIND_ARCHER_0TH_LINK_SKILLS } from './0th.js'
import { WIND_ARCHER_1ST_SIM_SKILLS, WIND_ARCHER_1ST_PASSIVE_SKILLS, WIND_ARCHER_1ST_BUFFS, WIND_ARCHER_1ST_BATTLE_BUFFS } from './1st.js'
import { WIND_ARCHER_2ND_SIM_SKILLS, WIND_ARCHER_2ND_PASSIVE_SKILLS, WIND_ARCHER_2ND_BUFFS, WIND_ARCHER_2ND_BATTLE_BUFFS, WIND_ARCHER_2ND_VMATRIX_SKILLS } from './2nd.js'
import { WIND_ARCHER_3RD_SIM_SKILLS, WIND_ARCHER_3RD_PASSIVE_SKILLS, WIND_ARCHER_3RD_BUFFS, WIND_ARCHER_3RD_BATTLE_BUFFS, WIND_ARCHER_3RD_VMATRIX_SKILLS } from './3rd.js'
import { WIND_ARCHER_4TH_SIM_SKILLS, WIND_ARCHER_4TH_PASSIVE_SKILLS, WIND_ARCHER_4TH_BUFFS, WIND_ARCHER_4TH_BATTLE_BUFFS, WIND_ARCHER_4TH_VMATRIX_SKILLS } from './4th.js'
import { WIND_ARCHER_5TH_SIM_SKILLS, WIND_ARCHER_5TH_PASSIVE_SKILLS, WIND_ARCHER_5TH_BUFFS, WIND_ARCHER_5TH_BATTLE_BUFFS, WIND_ARCHER_5TH_VMATRIX_SKILLS } from './5th.js'
import { WIND_ARCHER_6TH_SIM_SKILLS, WIND_ARCHER_6TH_PASSIVE_SKILLS, WIND_ARCHER_6TH_BUFFS, WIND_ARCHER_6TH_BATTLE_BUFFS, WIND_ARCHER_6TH_VMATRIX_SKILLS } from './6th.js'
import { WIND_ARCHER_HYPER_SKILLS, WIND_ARCHER_HYPER_ACTIVE_SKILLS } from './hyper.js'

export const WIND_ARCHER_SKILLS = [
  ...WIND_ARCHER_0TH_SIM_SKILLS, ...WIND_ARCHER_0TH_PASSIVE_SKILLS, ...WIND_ARCHER_0TH_LINK_SKILLS,
  ...WIND_ARCHER_1ST_SIM_SKILLS, ...WIND_ARCHER_1ST_PASSIVE_SKILLS, ...WIND_ARCHER_1ST_BUFFS, ...WIND_ARCHER_1ST_BATTLE_BUFFS,
  ...WIND_ARCHER_2ND_SIM_SKILLS, ...WIND_ARCHER_2ND_PASSIVE_SKILLS, ...WIND_ARCHER_2ND_BUFFS, ...WIND_ARCHER_2ND_BATTLE_BUFFS, ...WIND_ARCHER_2ND_VMATRIX_SKILLS,
  ...WIND_ARCHER_3RD_SIM_SKILLS, ...WIND_ARCHER_3RD_PASSIVE_SKILLS, ...WIND_ARCHER_3RD_BUFFS, ...WIND_ARCHER_3RD_BATTLE_BUFFS, ...WIND_ARCHER_3RD_VMATRIX_SKILLS,
  ...WIND_ARCHER_4TH_SIM_SKILLS, ...WIND_ARCHER_4TH_PASSIVE_SKILLS, ...WIND_ARCHER_4TH_BUFFS, ...WIND_ARCHER_4TH_BATTLE_BUFFS, ...WIND_ARCHER_4TH_VMATRIX_SKILLS,
  ...WIND_ARCHER_5TH_SIM_SKILLS, ...WIND_ARCHER_5TH_PASSIVE_SKILLS, ...WIND_ARCHER_5TH_BUFFS, ...WIND_ARCHER_5TH_BATTLE_BUFFS, ...WIND_ARCHER_5TH_VMATRIX_SKILLS,
  ...WIND_ARCHER_6TH_SIM_SKILLS, ...WIND_ARCHER_6TH_PASSIVE_SKILLS, ...WIND_ARCHER_6TH_BUFFS, ...WIND_ARCHER_6TH_BATTLE_BUFFS, ...WIND_ARCHER_6TH_VMATRIX_SKILLS,
  ...WIND_ARCHER_HYPER_SKILLS,
  ...WIND_ARCHER_HYPER_ACTIVE_SKILLS,
]

export const WIND_ARCHER_SIM_SKILLS = [
  ...WIND_ARCHER_0TH_SIM_SKILLS,
  ...WIND_ARCHER_1ST_SIM_SKILLS,
  ...WIND_ARCHER_2ND_SIM_SKILLS,
  ...WIND_ARCHER_3RD_SIM_SKILLS,
  ...WIND_ARCHER_4TH_SIM_SKILLS,
  ...WIND_ARCHER_5TH_SIM_SKILLS,
  ...WIND_ARCHER_6TH_SIM_SKILLS,
]

export const WIND_ARCHER_PASSIVE_SKILLS = [
  ...WIND_ARCHER_0TH_PASSIVE_SKILLS,
  ...WIND_ARCHER_1ST_PASSIVE_SKILLS,
  ...WIND_ARCHER_2ND_PASSIVE_SKILLS,
  ...WIND_ARCHER_3RD_PASSIVE_SKILLS,
  ...WIND_ARCHER_4TH_PASSIVE_SKILLS,
  ...WIND_ARCHER_5TH_PASSIVE_SKILLS,
  ...WIND_ARCHER_6TH_PASSIVE_SKILLS,
  ...WIND_ARCHER_HYPER_ACTIVE_SKILLS.filter((s) => s.cp?.role === 'passive'),
]

export const WIND_ARCHER_BUFFS = [
  ...WIND_ARCHER_1ST_BUFFS,
  ...WIND_ARCHER_2ND_BUFFS,
  ...WIND_ARCHER_3RD_BUFFS,
  ...WIND_ARCHER_4TH_BUFFS,
  ...WIND_ARCHER_5TH_BUFFS,
  ...WIND_ARCHER_6TH_BUFFS,
]

export const WIND_ARCHER_BATTLE_BUFFS = [
  ...WIND_ARCHER_1ST_BATTLE_BUFFS,
  ...WIND_ARCHER_2ND_BATTLE_BUFFS,
  ...WIND_ARCHER_3RD_BATTLE_BUFFS,
  ...WIND_ARCHER_4TH_BATTLE_BUFFS,
  ...WIND_ARCHER_5TH_BATTLE_BUFFS,
  ...WIND_ARCHER_6TH_BATTLE_BUFFS,
]

export const WIND_ARCHER_VMATRIX_SKILLS = [
  ...WIND_ARCHER_2ND_VMATRIX_SKILLS,
  ...WIND_ARCHER_3RD_VMATRIX_SKILLS,
  ...WIND_ARCHER_4TH_VMATRIX_SKILLS,
  ...WIND_ARCHER_5TH_VMATRIX_SKILLS,
  ...WIND_ARCHER_6TH_VMATRIX_SKILLS,
]

export const WIND_ARCHER_HYPER_SKILLS_ALL = WIND_ARCHER_HYPER_SKILLS

export const WIND_ARCHER_LINK_SKILLS = WIND_ARCHER_0TH_LINK_SKILLS
