// 全職業共通 barrel — 彙整 0~6 轉 + titles
//
// 對外 API 沿用舊命名:
//   ALL_JOBS_TOGGLE_SKILLS  — SKILLS 側欄 toggle 型
//   ALL_JOBS_BUFFS          — CP Buff 面板
//   ALL_JOBS_VMATRIX_SKILLS — V 矩陣 (通用)
// 稱號 (Title) 已獨立至 src/constants/titles.js
//   ALL_JOBS_BATTLE_BUFFS   — 實戰 buff (目前通用層無條目)
//   ALL_JOBS_PASSIVE_SKILLS — 自動職業技能 (目前通用層無條目)

import {
  ALL_JOBS_0TH_TOGGLE_SKILLS, ALL_JOBS_0TH_BUFFS, ALL_JOBS_0TH_VMATRIX_SKILLS,
  ALL_JOBS_0TH_BATTLE_BUFFS, ALL_JOBS_0TH_PASSIVE_SKILLS,
} from './0th.js'
import {
  ALL_JOBS_1ST_TOGGLE_SKILLS, ALL_JOBS_1ST_BUFFS, ALL_JOBS_1ST_VMATRIX_SKILLS,
  ALL_JOBS_1ST_BATTLE_BUFFS, ALL_JOBS_1ST_PASSIVE_SKILLS,
} from './1st.js'
import {
  ALL_JOBS_2ND_TOGGLE_SKILLS, ALL_JOBS_2ND_BUFFS, ALL_JOBS_2ND_VMATRIX_SKILLS,
  ALL_JOBS_2ND_BATTLE_BUFFS, ALL_JOBS_2ND_PASSIVE_SKILLS,
} from './2nd.js'
import {
  ALL_JOBS_3RD_TOGGLE_SKILLS, ALL_JOBS_3RD_BUFFS, ALL_JOBS_3RD_VMATRIX_SKILLS,
  ALL_JOBS_3RD_BATTLE_BUFFS, ALL_JOBS_3RD_PASSIVE_SKILLS,
} from './3rd.js'
import {
  ALL_JOBS_4TH_TOGGLE_SKILLS, ALL_JOBS_4TH_BUFFS, ALL_JOBS_4TH_VMATRIX_SKILLS,
  ALL_JOBS_4TH_BATTLE_BUFFS, ALL_JOBS_4TH_PASSIVE_SKILLS,
} from './4th.js'
import {
  ALL_JOBS_5TH_TOGGLE_SKILLS, ALL_JOBS_5TH_BUFFS, ALL_JOBS_5TH_VMATRIX_SKILLS,
  ALL_JOBS_5TH_BATTLE_BUFFS, ALL_JOBS_5TH_PASSIVE_SKILLS,
} from './5th.js'
import {
  ALL_JOBS_6TH_TOGGLE_SKILLS, ALL_JOBS_6TH_BUFFS, ALL_JOBS_6TH_VMATRIX_SKILLS,
  ALL_JOBS_6TH_BATTLE_BUFFS, ALL_JOBS_6TH_PASSIVE_SKILLS,
} from './6th.js'
// titles 已獨立至 src/constants/titles.js,非 skills 系統一員

export const ALL_JOBS_TOGGLE_SKILLS = [
  ...ALL_JOBS_0TH_TOGGLE_SKILLS,
  ...ALL_JOBS_1ST_TOGGLE_SKILLS,
  ...ALL_JOBS_2ND_TOGGLE_SKILLS,
  ...ALL_JOBS_3RD_TOGGLE_SKILLS,
  ...ALL_JOBS_4TH_TOGGLE_SKILLS,
  ...ALL_JOBS_5TH_TOGGLE_SKILLS,
  ...ALL_JOBS_6TH_TOGGLE_SKILLS,
]

export const ALL_JOBS_BUFFS = [
  ...ALL_JOBS_0TH_BUFFS,
  ...ALL_JOBS_1ST_BUFFS,
  ...ALL_JOBS_2ND_BUFFS,
  ...ALL_JOBS_3RD_BUFFS,
  ...ALL_JOBS_4TH_BUFFS,
  ...ALL_JOBS_5TH_BUFFS,
  ...ALL_JOBS_6TH_BUFFS,
]

export const ALL_JOBS_VMATRIX_SKILLS = [
  ...ALL_JOBS_0TH_VMATRIX_SKILLS,
  ...ALL_JOBS_1ST_VMATRIX_SKILLS,
  ...ALL_JOBS_2ND_VMATRIX_SKILLS,
  ...ALL_JOBS_3RD_VMATRIX_SKILLS,
  ...ALL_JOBS_4TH_VMATRIX_SKILLS,
  ...ALL_JOBS_5TH_VMATRIX_SKILLS,
  ...ALL_JOBS_6TH_VMATRIX_SKILLS,
]

export const ALL_JOBS_BATTLE_BUFFS = [
  ...ALL_JOBS_0TH_BATTLE_BUFFS,
  ...ALL_JOBS_1ST_BATTLE_BUFFS,
  ...ALL_JOBS_2ND_BATTLE_BUFFS,
  ...ALL_JOBS_3RD_BATTLE_BUFFS,
  ...ALL_JOBS_4TH_BATTLE_BUFFS,
  ...ALL_JOBS_5TH_BATTLE_BUFFS,
  ...ALL_JOBS_6TH_BATTLE_BUFFS,
]

// 命名避開 jobs/index.js 的 ALL_JOBS_PASSIVE_SKILLS(後者是跨職業 passive 總合)
export const ALL_JOBS_COMMON_PASSIVE_SKILLS = [
  ...ALL_JOBS_0TH_PASSIVE_SKILLS,
  ...ALL_JOBS_1ST_PASSIVE_SKILLS,
  ...ALL_JOBS_2ND_PASSIVE_SKILLS,
  ...ALL_JOBS_3RD_PASSIVE_SKILLS,
  ...ALL_JOBS_4TH_PASSIVE_SKILLS,
  ...ALL_JOBS_5TH_PASSIVE_SKILLS,
  ...ALL_JOBS_6TH_PASSIVE_SKILLS,
]

