// 冒險家盜賊共通 barrel — 彙整 0~6 轉
// 適用職業:shadower / nightlord / dualblade

import { ADVENTURER_THIEF_0TH_TOGGLE_SKILLS, ADVENTURER_THIEF_0TH_BUFFS, ADVENTURER_THIEF_0TH_VMATRIX_SKILLS, ADVENTURER_THIEF_0TH_BATTLE_BUFFS, ADVENTURER_THIEF_0TH_PASSIVE_SKILLS } from './0th.js'
import { ADVENTURER_THIEF_1ST_TOGGLE_SKILLS, ADVENTURER_THIEF_1ST_BUFFS, ADVENTURER_THIEF_1ST_VMATRIX_SKILLS, ADVENTURER_THIEF_1ST_BATTLE_BUFFS, ADVENTURER_THIEF_1ST_PASSIVE_SKILLS } from './1st.js'
import { ADVENTURER_THIEF_2ND_TOGGLE_SKILLS, ADVENTURER_THIEF_2ND_BUFFS, ADVENTURER_THIEF_2ND_VMATRIX_SKILLS, ADVENTURER_THIEF_2ND_BATTLE_BUFFS, ADVENTURER_THIEF_2ND_PASSIVE_SKILLS } from './2nd.js'
import { ADVENTURER_THIEF_3RD_TOGGLE_SKILLS, ADVENTURER_THIEF_3RD_BUFFS, ADVENTURER_THIEF_3RD_VMATRIX_SKILLS, ADVENTURER_THIEF_3RD_BATTLE_BUFFS, ADVENTURER_THIEF_3RD_PASSIVE_SKILLS } from './3rd.js'
import { ADVENTURER_THIEF_4TH_TOGGLE_SKILLS, ADVENTURER_THIEF_4TH_BUFFS, ADVENTURER_THIEF_4TH_VMATRIX_SKILLS, ADVENTURER_THIEF_4TH_BATTLE_BUFFS, ADVENTURER_THIEF_4TH_PASSIVE_SKILLS } from './4th.js'
import { ADVENTURER_THIEF_5TH_TOGGLE_SKILLS, ADVENTURER_THIEF_5TH_BUFFS, ADVENTURER_THIEF_5TH_VMATRIX_SKILLS, ADVENTURER_THIEF_5TH_BATTLE_BUFFS, ADVENTURER_THIEF_5TH_PASSIVE_SKILLS } from './5th.js'
import { ADVENTURER_THIEF_6TH_TOGGLE_SKILLS, ADVENTURER_THIEF_6TH_BUFFS, ADVENTURER_THIEF_6TH_VMATRIX_SKILLS, ADVENTURER_THIEF_6TH_BATTLE_BUFFS, ADVENTURER_THIEF_6TH_PASSIVE_SKILLS } from './6th.js'

export const ADVENTURER_THIEF_PASSIVE_SKILLS = [
  ...ADVENTURER_THIEF_0TH_PASSIVE_SKILLS, ...ADVENTURER_THIEF_1ST_PASSIVE_SKILLS,
  ...ADVENTURER_THIEF_2ND_PASSIVE_SKILLS, ...ADVENTURER_THIEF_3RD_PASSIVE_SKILLS,
  ...ADVENTURER_THIEF_4TH_PASSIVE_SKILLS, ...ADVENTURER_THIEF_5TH_PASSIVE_SKILLS,
  ...ADVENTURER_THIEF_6TH_PASSIVE_SKILLS,
]

export const ADVENTURER_THIEF_TOGGLE_SKILLS = [
  ...ADVENTURER_THIEF_0TH_TOGGLE_SKILLS, ...ADVENTURER_THIEF_1ST_TOGGLE_SKILLS,
  ...ADVENTURER_THIEF_2ND_TOGGLE_SKILLS, ...ADVENTURER_THIEF_3RD_TOGGLE_SKILLS,
  ...ADVENTURER_THIEF_4TH_TOGGLE_SKILLS, ...ADVENTURER_THIEF_5TH_TOGGLE_SKILLS,
  ...ADVENTURER_THIEF_6TH_TOGGLE_SKILLS,
]

export const ADVENTURER_THIEF_BUFFS = [
  ...ADVENTURER_THIEF_0TH_BUFFS, ...ADVENTURER_THIEF_1ST_BUFFS,
  ...ADVENTURER_THIEF_2ND_BUFFS, ...ADVENTURER_THIEF_3RD_BUFFS,
  ...ADVENTURER_THIEF_4TH_BUFFS, ...ADVENTURER_THIEF_5TH_BUFFS,
  ...ADVENTURER_THIEF_6TH_BUFFS,
]

export const ADVENTURER_THIEF_VMATRIX_SKILLS = [
  ...ADVENTURER_THIEF_0TH_VMATRIX_SKILLS, ...ADVENTURER_THIEF_1ST_VMATRIX_SKILLS,
  ...ADVENTURER_THIEF_2ND_VMATRIX_SKILLS, ...ADVENTURER_THIEF_3RD_VMATRIX_SKILLS,
  ...ADVENTURER_THIEF_4TH_VMATRIX_SKILLS, ...ADVENTURER_THIEF_5TH_VMATRIX_SKILLS,
  ...ADVENTURER_THIEF_6TH_VMATRIX_SKILLS,
]

export const ADVENTURER_THIEF_BATTLE_BUFFS = [
  ...ADVENTURER_THIEF_0TH_BATTLE_BUFFS, ...ADVENTURER_THIEF_1ST_BATTLE_BUFFS,
  ...ADVENTURER_THIEF_2ND_BATTLE_BUFFS, ...ADVENTURER_THIEF_3RD_BATTLE_BUFFS,
  ...ADVENTURER_THIEF_4TH_BATTLE_BUFFS, ...ADVENTURER_THIEF_5TH_BATTLE_BUFFS,
  ...ADVENTURER_THIEF_6TH_BATTLE_BUFFS,
]
