// Shadower — 彙整 barrel

import { SHADOWER_0TH_SIM_SKILLS, SHADOWER_0TH_PASSIVE_SKILLS, SHADOWER_0TH_LINK_SKILLS } from './0th.js'
import { SHADOWER_1ST_SIM_SKILLS, SHADOWER_1ST_PASSIVE_SKILLS, SHADOWER_1ST_BUFFS, SHADOWER_1ST_BATTLE_BUFFS } from './1st.js'
import { SHADOWER_2ND_SIM_SKILLS, SHADOWER_2ND_PASSIVE_SKILLS, SHADOWER_2ND_BUFFS, SHADOWER_2ND_BATTLE_BUFFS, SHADOWER_2ND_VMATRIX_SKILLS } from './2nd.js'
import { SHADOWER_3RD_SIM_SKILLS, SHADOWER_3RD_PASSIVE_SKILLS, SHADOWER_3RD_BUFFS, SHADOWER_3RD_BATTLE_BUFFS, SHADOWER_3RD_VMATRIX_SKILLS } from './3rd.js'
import { SHADOWER_4TH_SIM_SKILLS, SHADOWER_4TH_PASSIVE_SKILLS, SHADOWER_4TH_BUFFS, SHADOWER_4TH_BATTLE_BUFFS, SHADOWER_4TH_VMATRIX_SKILLS } from './4th.js'
import { SHADOWER_5TH_SIM_SKILLS, SHADOWER_5TH_PASSIVE_SKILLS, SHADOWER_5TH_BUFFS, SHADOWER_5TH_BATTLE_BUFFS, SHADOWER_5TH_VMATRIX_SKILLS } from './5th.js'
import { SHADOWER_6TH_SIM_SKILLS, SHADOWER_6TH_PASSIVE_SKILLS, SHADOWER_6TH_BUFFS, SHADOWER_6TH_BATTLE_BUFFS, SHADOWER_6TH_VMATRIX_SKILLS } from './6th.js'
import { SHADOWER_HYPER_SKILLS, SHADOWER_HYPER_ACTIVE_SKILLS } from './hyper.js'

export const SHADOWER_SKILLS = [
  ...SHADOWER_0TH_SIM_SKILLS, ...SHADOWER_0TH_PASSIVE_SKILLS, ...SHADOWER_0TH_LINK_SKILLS,
  ...SHADOWER_1ST_SIM_SKILLS, ...SHADOWER_1ST_PASSIVE_SKILLS, ...SHADOWER_1ST_BUFFS, ...SHADOWER_1ST_BATTLE_BUFFS,
  ...SHADOWER_2ND_SIM_SKILLS, ...SHADOWER_2ND_PASSIVE_SKILLS, ...SHADOWER_2ND_BUFFS, ...SHADOWER_2ND_BATTLE_BUFFS, ...SHADOWER_2ND_VMATRIX_SKILLS,
  ...SHADOWER_3RD_SIM_SKILLS, ...SHADOWER_3RD_PASSIVE_SKILLS, ...SHADOWER_3RD_BUFFS, ...SHADOWER_3RD_BATTLE_BUFFS, ...SHADOWER_3RD_VMATRIX_SKILLS,
  ...SHADOWER_4TH_SIM_SKILLS, ...SHADOWER_4TH_PASSIVE_SKILLS, ...SHADOWER_4TH_BUFFS, ...SHADOWER_4TH_BATTLE_BUFFS, ...SHADOWER_4TH_VMATRIX_SKILLS,
  ...SHADOWER_5TH_SIM_SKILLS, ...SHADOWER_5TH_PASSIVE_SKILLS, ...SHADOWER_5TH_BUFFS, ...SHADOWER_5TH_BATTLE_BUFFS, ...SHADOWER_5TH_VMATRIX_SKILLS,
  ...SHADOWER_6TH_SIM_SKILLS, ...SHADOWER_6TH_PASSIVE_SKILLS, ...SHADOWER_6TH_BUFFS, ...SHADOWER_6TH_BATTLE_BUFFS, ...SHADOWER_6TH_VMATRIX_SKILLS,
  ...SHADOWER_HYPER_SKILLS,
  ...SHADOWER_HYPER_ACTIVE_SKILLS,
]

export const SHADOWER_SIM_SKILLS = [
  ...SHADOWER_0TH_SIM_SKILLS,
  ...SHADOWER_1ST_SIM_SKILLS,
  ...SHADOWER_2ND_SIM_SKILLS,
  ...SHADOWER_3RD_SIM_SKILLS,
  ...SHADOWER_4TH_SIM_SKILLS,
  ...SHADOWER_5TH_SIM_SKILLS,
  ...SHADOWER_6TH_SIM_SKILLS,
]

export const SHADOWER_PASSIVE_SKILLS = [
  ...SHADOWER_0TH_PASSIVE_SKILLS,
  ...SHADOWER_1ST_PASSIVE_SKILLS,
  ...SHADOWER_2ND_PASSIVE_SKILLS,
  ...SHADOWER_3RD_PASSIVE_SKILLS,
  ...SHADOWER_4TH_PASSIVE_SKILLS,
  ...SHADOWER_5TH_PASSIVE_SKILLS,
  ...SHADOWER_6TH_PASSIVE_SKILLS,
  ...SHADOWER_HYPER_ACTIVE_SKILLS.filter((s) => s.cp?.role === 'passive'),
]

export const SHADOWER_BUFFS = [
  ...SHADOWER_1ST_BUFFS,
  ...SHADOWER_2ND_BUFFS,
  ...SHADOWER_3RD_BUFFS,
  ...SHADOWER_4TH_BUFFS,
  ...SHADOWER_5TH_BUFFS,
  ...SHADOWER_6TH_BUFFS,
]

export const SHADOWER_BATTLE_BUFFS = [
  ...SHADOWER_1ST_BATTLE_BUFFS,
  ...SHADOWER_2ND_BATTLE_BUFFS,
  ...SHADOWER_3RD_BATTLE_BUFFS,
  ...SHADOWER_4TH_BATTLE_BUFFS,
  ...SHADOWER_5TH_BATTLE_BUFFS,
  ...SHADOWER_6TH_BATTLE_BUFFS,
]

export const SHADOWER_VMATRIX_SKILLS = [
  ...SHADOWER_2ND_VMATRIX_SKILLS,
  ...SHADOWER_3RD_VMATRIX_SKILLS,
  ...SHADOWER_4TH_VMATRIX_SKILLS,
  ...SHADOWER_5TH_VMATRIX_SKILLS,
  ...SHADOWER_6TH_VMATRIX_SKILLS,
]

export const SHADOWER_HYPER_SKILLS_ALL = SHADOWER_HYPER_SKILLS

export const SHADOWER_LINK_SKILLS = SHADOWER_0TH_LINK_SKILLS
