// {JOB_NAME} — 彙整 barrel
// 複製此資料夾當作新職業範本,再把 TEMPLATE_ 前綴改成職業 key。
//
// 每個職業 index.js 的責任:
//   1. 匯集此職業 0 ~ 6 轉 + Hyper 的所有技能
//   2. 對外暴露命名常數,供頂層 skills/index.js 合併
//
// 慣例輸出:
//   <JOB>_SIM_SKILLS       — 戰鬥模擬 (有 hit/burn/castDelay)
//   <JOB>_PASSIVE_SKILLS   — CP 自動 passive (SKILLS passive: true)
//   <JOB>_BUFFS            — CP 側欄 buff
//   <JOB>_BATTLE_BUFFS     — 戰鬥模擬 buff
//   <JOB>_VMATRIX_SKILLS   — V 矩陣
//   <JOB>_HYPER_SKILLS     — 超技能
//   <JOB>_LINK_SKILLS      — Link Skill 索引 (引用 data/linkSkills.js)
//   <JOB>_ALL_SKILLS       — 以 advancement 分組後的總表 (供 UI 檢視)

import { TEMPLATE_0TH_SIM_SKILLS, TEMPLATE_0TH_PASSIVE_SKILLS, TEMPLATE_0TH_LINK_SKILLS } from './0th.js'
import { TEMPLATE_1ST_SIM_SKILLS, TEMPLATE_1ST_PASSIVE_SKILLS, TEMPLATE_1ST_BUFFS, TEMPLATE_1ST_BATTLE_BUFFS } from './1st.js'
import { TEMPLATE_2ND_SIM_SKILLS, TEMPLATE_2ND_PASSIVE_SKILLS, TEMPLATE_2ND_BUFFS, TEMPLATE_2ND_BATTLE_BUFFS, TEMPLATE_2ND_VMATRIX_SKILLS } from './2nd.js'
import { TEMPLATE_3RD_SIM_SKILLS, TEMPLATE_3RD_PASSIVE_SKILLS, TEMPLATE_3RD_BUFFS, TEMPLATE_3RD_BATTLE_BUFFS, TEMPLATE_3RD_VMATRIX_SKILLS } from './3rd.js'
import { TEMPLATE_4TH_SIM_SKILLS, TEMPLATE_4TH_PASSIVE_SKILLS, TEMPLATE_4TH_BUFFS, TEMPLATE_4TH_BATTLE_BUFFS, TEMPLATE_4TH_VMATRIX_SKILLS } from './4th.js'
import { TEMPLATE_5TH_SIM_SKILLS, TEMPLATE_5TH_PASSIVE_SKILLS, TEMPLATE_5TH_BUFFS, TEMPLATE_5TH_BATTLE_BUFFS, TEMPLATE_5TH_VMATRIX_SKILLS } from './5th.js'
import { TEMPLATE_6TH_SIM_SKILLS, TEMPLATE_6TH_PASSIVE_SKILLS, TEMPLATE_6TH_BUFFS, TEMPLATE_6TH_BATTLE_BUFFS, TEMPLATE_6TH_VMATRIX_SKILLS } from './6th.js'
import { TEMPLATE_HYPER_SKILLS } from './hyper.js'

export const TEMPLATE_SIM_SKILLS = [
  ...TEMPLATE_0TH_SIM_SKILLS,
  ...TEMPLATE_1ST_SIM_SKILLS,
  ...TEMPLATE_2ND_SIM_SKILLS,
  ...TEMPLATE_3RD_SIM_SKILLS,
  ...TEMPLATE_4TH_SIM_SKILLS,
  ...TEMPLATE_5TH_SIM_SKILLS,
  ...TEMPLATE_6TH_SIM_SKILLS,
]

export const TEMPLATE_PASSIVE_SKILLS = [
  ...TEMPLATE_0TH_PASSIVE_SKILLS,
  ...TEMPLATE_1ST_PASSIVE_SKILLS,
  ...TEMPLATE_2ND_PASSIVE_SKILLS,
  ...TEMPLATE_3RD_PASSIVE_SKILLS,
  ...TEMPLATE_4TH_PASSIVE_SKILLS,
  ...TEMPLATE_5TH_PASSIVE_SKILLS,
  ...TEMPLATE_6TH_PASSIVE_SKILLS,
]

export const TEMPLATE_BUFFS = [
  ...TEMPLATE_1ST_BUFFS,
  ...TEMPLATE_2ND_BUFFS,
  ...TEMPLATE_3RD_BUFFS,
  ...TEMPLATE_4TH_BUFFS,
  ...TEMPLATE_5TH_BUFFS,
  ...TEMPLATE_6TH_BUFFS,
]

export const TEMPLATE_BATTLE_BUFFS = [
  ...TEMPLATE_1ST_BATTLE_BUFFS,
  ...TEMPLATE_2ND_BATTLE_BUFFS,
  ...TEMPLATE_3RD_BATTLE_BUFFS,
  ...TEMPLATE_4TH_BATTLE_BUFFS,
  ...TEMPLATE_5TH_BATTLE_BUFFS,
  ...TEMPLATE_6TH_BATTLE_BUFFS,
]

export const TEMPLATE_VMATRIX_SKILLS = [
  ...TEMPLATE_2ND_VMATRIX_SKILLS,
  ...TEMPLATE_3RD_VMATRIX_SKILLS,
  ...TEMPLATE_4TH_VMATRIX_SKILLS,
  ...TEMPLATE_5TH_VMATRIX_SKILLS,
  ...TEMPLATE_6TH_VMATRIX_SKILLS,
]

export const TEMPLATE_HYPER_SKILLS_ALL = TEMPLATE_HYPER_SKILLS

export const TEMPLATE_LINK_SKILLS = TEMPLATE_0TH_LINK_SKILLS
